#! /bin/zsh

export EMAIL="southgate@gmail.com"
export FULLNAME="Alex Southgate"

#export GIT_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$DEBEMAIL
#export GIT_COMMITTER_EMAIL=$DEBEMAIL

export CVS_RSH="ssh"
export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export CCACHE_DIR=$HOME/.ccache

export LC_MESSAGES=C
export LC_ALL=
unset VERBOSE
